
extra_fn_clean_exts:
   #- type: remove
   #  pattern: _R1_001
   #- type: remove
   #  pattern: _R2_001
   - type: remove
     pattern: _bowtie2.err
   - type: remove
     pattern: _001
  # - type: remove
  #   pattern: _trimmed_R1
  # - type: remove
  #   pattern: _trimmed_R2
   - type: remove
     pattern: _rsem
   - type: remove
     pattern: _star.genome
   - type: remove
     pattern: Sample_
   - type: remove
     pattern: _R1_5million_screen
   - type: remove
     pattern: _R2_5million_screen
fn_ignore_files:
   - '*_1p_Log.*'
table_columns_visible:
     FastQC:
         percent_duplicates: False
table_columns_visible:
    FastQC (raw):
        percent_duplicates: False
        percent_gc: False
    FastQC (trimmed):
        percent_duplicates: False
        percent_gc: False
module_order:
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*R1_001_fastqc.zip'
            - '*R2_001_fastqc.zip'
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*trimmed_R1_fastqc.zip'
            - '*trimmed_R2_fastqc.zip'

fastqscreen_simpleplot: true

#remove_sections:
#    - fastqc_status_checks
