cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem='{resources.mem}'
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards.tranckingID}-%j.out
    --no-requeue
default-resources:
  - partition=norm
  - mem='32GB'
executor: cluster-generic
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 600
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
