# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.csv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "/path/to/config/samples.csv"
rawpath: "/path/to/rawdata"
analysispath: "/path/to/analysis"
projectname: "projectName"
adapters: "resource/TruSeq_and_nextera_adapters.fa"
fastqscreenConf: "resource/fastq_screen_slurm.conf"
multiqcConf: "resource/config_multiQC.yaml"
fastqscreenConf_hsa_miRNA: "resource/fastq_screen_hsa_small_RNA_slurm.conf"
fastqscreenConf_mmu_miRNA: "resource/fastq_screen_mmu_small_RNA_slurm.conf"
refgen_hsa_miRNA: "/path/to/reference/hg38/BOWTIE/index"
refgen_mmu_miRNA: "/path/to/reference/mm10/BOWTIE/index"
mirdeep2_hsa_genome: "/path/to/reference/hg38/fasta"
mirdeep2_mmu_genome: "/path/to/reference/mm10/fasta"
mature_hsa_miRNA: "resource/mirbaseV22_mature_human.fa"
mature_mmu_miRNA: "resource/mirbaseV22_mature_mouse.fa"
hairpin_hsa_miRNA: "resource/mirbaseV22_hairpin_human.fa"
hairpin_mmu_miRNA: "resource/mirbaseV22_hairpin_mouse.fa"
